### PR TITLE
Allow smaller widget sizes for #194 

### PR DESCRIPTION
**Pull request by l3d00m**
Allow widget to be resized to 2x3. If width is under 4 columns, hide contact avatars.  
The code is probably a bit messy because I'm new to Java.

### CODE REVIEW

**Comment by moezbhatti** [comment]
Can you squash the commits so it shows them as one?

**Comment by l3d00m** [comment]
I can't find a way to do that. Do you have a tutorial or somthing?

**Comment by moezbhatti** [comment]
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by l3d00m** [comment]
This does not show the "merge remote tracking..."  commits, it only show the last not merge-specific commits.

**Pull request merged**
