### PR TITLE
Add a option to hide sender too in notifications

### PR DESCRIPTION
**Pull request by l3d00m**
Strings should probably be changed (bad english). Fix for #148 
I made a list preference instead of adding another checkbox.

### CODE REVIEW

**Comment by xavihernandez** [comment]
Thanks for this implementation, I hope it get accepted soon :).

By the way I have noticed some bug when "Private notifications" are enabled. The first message is hidden, but if you receive a message from another person, then content is not hidden.

**Comment by l3d00m** [comment]
No problem, I'm hoping this too. Will look into it.

**Comment by xavihernandez** [comment]
Thanks, it is easy enough to reproduce this bug.

**Comment by l3d00m** [comment]
Fixed

**Comment by xavihernandez** [comment]
You the man.
It was really easy =)

**Comment by l3d00m** [comment]
Yeah, it just was a little bit hidden (for me).

**Comment by xavihernandez** [comment]
Oh ok. It seems that they named their methiods with explicit names it's good!

**Comment by moezbhatti** [comment]
When there's multiple messages received from the same person, then their name still shows up

**Comment by l3d00m** [comment]
Fixed

**Comment by l3d00m** [comment]
Not. One moment please

**Comment by xavihernandez** [comment]
Great!

**Comment by xavihernandez** [comment]
thanks @l3d00m

**Comment by l3d00m** [comment]
no problem :)

**Pull request merged**
