### PR TITLE
Add option to select Google's Lato Font Family.

### PR DESCRIPTION
**Pull request by KyleGospo**
Adds the option to select Google's Lato Font
Changes RobotoTextViewUtils and RobotoTypefaceManager to be generic.
Changes font family option text to reflect actual family. IE:
Regular -> Roboto Regular.

This translation is complete for most languages. Languages vastly
different from English will need some small changes in this area.

Preview: https://i.imgur.com/Mz6goLI.png

### CODE REVIEW

**Comment by moezbhatti** [comment]
This is great, thanks for going so in-depth with everything!

There's only one weird issue that I noticed. If a message bubble has only one line of text, then the text isn't aligned to the vertical center of the bubble.

This can be fixed by adding `android:gravity="center_vertical"` to `@id/text_view` in `layout/list_item_message_out` and `list_item_message_in`

**Comment by KyleGospo** [comment]
Hi Moez, thanks for the heads up! I just added those lines and squashed it back into a single commit.

**Comment by moezbhatti** [comment]
Awesome!

Last thing: This PR is trying to merge into `master`. Could you close it and create a PR into `develop` instead?

**Comment by KyleGospo** [comment]
-Removed to re-base on develop

**Pull request closed without merging**
