### PR TITLE
Fix for #142, random patches

### LINKED ISSUE #142: Writting Issue
android ICS
When I write it doesn't show suggestions when t9 is on and when I press space it makes the first letter big, like when you start a new sentence.

### PR DESCRIPTION
**Pull request by l3d00m**
This should fix #142, it's not the best solution though.
It's not possible to use multiline mode and to use the enter key as Action_send so this is the workaround: http://stackoverflow.com/a/6772713/4026792

### CODE REVIEW

**Comment by moezbhatti** [comment]
Can you rebase and merge into master instead?
We're changing up the git flow, using master instead of develop now. I'm just leaving develop open until the current PRs have been merged

The reason I'm saying to rebase though is because some of these changes have already been made on master

**Comment by l3d00m** [comment]
Ok, I'll try to rebase it tomorrow. Never done it before but I hope it isn't that hard.

**Comment by moezbhatti** [comment]
Shouldn't be too bad, just make sure it contains the changes from #168

**Comment by l3d00m** [comment]
Change target branch

**Pull request closed without merging**
