### PR TITLE
Incomplete tweak to setTextChangedListener to use getNumPages

### PR DESCRIPTION
**Pull request by Verlet64**
I am waiting on stringbuilder methods to convert s, character sequence, to a
string for the  getNumPages method.

### CODE REVIEW

**Comment by Verlet64** [comment]
Christ, I'm somewhat scrubby at this, but the relevant change is change no.2; the rest I didn't see until now and have no idea how to get rid of.

**Comment by KyleGospo** [comment]
This may help you @Verlet64
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by moezbhatti** [comment]
What's wrong with just doing this?

    mLetterCount.setText((160 - length % 160) + "/" + (Utils.getNumPages((SmsHelper.getSendSettings(getContext())), s.toString())));

**Comment by moezbhatti** [comment]
Side note: Although it does solve the issue within that if/else block, it doesn't completely solve the issue because the other blocks are assuming a character limit of 160

**Comment by Verlet64** [comment]
Nothing wrong with it at all, just a bit of precaution, but really more me treating the code like a glass house heh. On your side note, that's absolutely true, and I'm looking at it and thinking could we not just use a %160 to wrap the value around (i.e 'modulo' the actual character count, and compare that to 160). Would that work?

**Pull request closed without merging**
