### PR TITLE
lint cleanup

### PR DESCRIPTION
**Pull request by l3d00m**

### CODE REVIEW

**Comment by l3d00m** [comment]
fixed

**Comment by moezbhatti** [comment]
I think it might be better to do this whole thing as smaller PRs

There's a small chance that the lint cleanup messed something up, but there's so many lines changed here that it'll be impossible to detect, so it could be kind of risky to merge this in

**Comment by l3d00m** [comment]
ok, i will start with the first commit (reformat code)

**Comment by moezbhatti** [comment]
Awesome, thanks

**Pull request closed without merging**
