### PR TITLE
add action button 'Call' to notification manager #401

### PR DESCRIPTION
**Pull request by redwerk**
@moezbhatti , i have added action button 'Call' to notify manager for this issue #401 , but i have a question for code snippet below, what exactly this function checks and is it necessary? Thanks!
```java
if (conversationPrefs.getCallButtonEnabled()) {
     Intent callIntent = new Intent(Intent.ACTION_CALL);
     callIntent.setData(Uri.parse("tel:" + message.mAddress));
     PendingIntent callPI = PendingIntent.getActivity(context, buildRequestCode(threadId, 3), callIntent, PendingIntent.FLAG_UPDATE_CURRENT);
     builder.addAction(R.drawable.ic_call, sRes.getString(R.string.call), callPI);
}
```

### CODE REVIEW

**Comment by moezbhatti** [comment]
The point of that is to check if the user has the call button enabled in their preferences, and if so, it'll add it to the notification. The reason it's a preference is because

1. Not everyone would use it. I know I wouldn't
2. It makes the notification actions strip very crowded when there's 3 buttons

**Comment by redwerk** [comment]
So, if i understand you correctly, this ability for issue #401 has already been added in code ? If not, can u explain what exactly need to do for this issue, thanks.

**Comment by moezbhatti** [comment]
That's unclear, actually. I'll get a clarification

**Comment by moezbhatti** [comment]
Yeah, that was actually what he was looking for. My bad, I should have recognized that and closed the issue sooner.

**Pull request closed without merging**
