### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by Kondra007**
Sorry, I can't translate at crowdin right now, hope anyone could do it.
This is not 100% Russian translation, but I've translated lots of new things and fixed some grammar mistakes.

### CODE REVIEW

**Comment by moezbhatti** [comment]
Hey, how come you can't translate using Crowdin?

It's much preferred to do the translations there, because then I don't need to worry about conflicts and I can just use the crowdin files and directly overwrite the ones in the project

**Comment by Kondra007** [comment]
Okay, I'll try to translate at Crowdin within several days

**Comment by moezbhatti** [comment]
Awesome, thank you!

**Comment by Kondra007** [comment]
@moezbhatti Could you give me the link to QKSMS project on Crowdin? I can't find it.

**Comment by moezbhatti** [comment]
The project got removed because of a stupid mistake I made, I'm working with the Crowdin team to get it back up

**Comment by Kondra007** [comment]
@moezbhatti ah, good luck with that!

**Pull request closed without merging**
