### PR TITLE
Fix spelling mistakes in German translation and add missing translations

### PR DESCRIPTION
**Pull request by pille1842**
- Fix a lot of spelling mistakes in the German strings file
- Add all that were missing in this version
- Consistently use "Unterhaltung" as the translation for "conversation"

### CODE REVIEW

**Comment by l3d00m** [comment]
Unterhaltung als Übersetzung hört sich gut an. Macht es Sinn QK-Reply zu übersetzen? Ich finde  QK-Reply hört sich besser an als QK-Antworten.

**Comment by pille1842** [comment]
@l3d00m I've replaced "QK-Antworten" with "QK Reply" - you're right, it sounds like a feature name and therefore shouldn't be translated.

**Comment by moezbhatti** [comment]
There are some merge issues, if you could fix them up then I'll go ahead with the merge

**Comment by moezbhatti** [comment]
I've manually added the changes to [Crowdin](https://crowdin.com/project/qksms)

If you'd like to make any further changes, please do them there rather than directly on the repo

**Comment by pille1842** [comment]
I have made some more changes (mostly complementing missing translations) in the Crowdin project. Glad that Crowdin was able to work it out!

**Pull request closed without merging**
