### PR TITLE
More random patches

### PR DESCRIPTION
**Pull request by mvdan**
Java 1.7 requires minSdk 8, so I think that's fine :)

### CODE REVIEW

**Comment by mvdan** [comment]
the default target `connectedCheck` fails since no devices are connected, removing it again.

**Comment by moezbhatti** [comment]
I need to verify that the code is no longer obfuscated, otherwise I want to keep mappings.txt file under version control

**Comment by mvdan** [comment]
I'm fairly certain it isn't, check `proguard-android.txt` in your SDK :) You can also add `-dontobfuscate` and `-dontoptimize` to your proguard file to be sure.

**Comment by moezbhatti** [comment]
I was looking into that before, but adding those lines ended up doubling the app size :/ So I opted to keep everything enabled

I'll check this out in about an hour, trying to get through some other PRs right now :)

**Comment by mvdan** [comment]
I stand corrected, obfuscation is on with `proguard-android.txt`. You have to disable it explicitly :(

I'll make the appropriate changes.

**Comment by moezbhatti** [comment]
Sweet, that'd be awesome

In my opinion, a smaller app size is more important than having no obfuscation

**Comment by mvdan** [comment]
The difference is about 200KB, just checked.

In my opinion no obfuscation wins, since it makes reporting issues much easier for users.

**Comment by moezbhatti** [comment]
Oh, really? Last I checked the difference was about 5MB. If it's just 200KB then I don't really care

**Comment by moezbhatti** [comment]
Awesome, just verified and t's not obfuscated and the app is still < 5MB

**Pull request merged**
