### PR TITLE
Removed two hard coded strings

### PR DESCRIPTION
**Pull request by l3d00m**

### CODE REVIEW

**Comment by moezbhatti** [comment]
Awesome

Can you add the german translations to Crowdin? These files will be overridden any time I update from Crowdin

**Comment by l3d00m** [comment]
I will look into crowdin from time to time (I've done this before too). I will also make some more pull requests when I have more time!

**Comment by moezbhatti** [comment]
Sounds good! I'll merge this in

**Comment by l3d00m** [comment]
Thanks! Do you have a link to the crowdin project?  I can't  find the old one anymore.

**Comment by moezbhatti** [comment]
Hm... it's not showing up for me

One second
Are you on our Slack channel? I can message you there

**Comment by l3d00m** [comment]
No I'm not. You can alternatively message me on reddit.com/u/l3d00m

**Comment by moezbhatti** [comment]
I'll let you know when I get the Crowdin thing sorted out, the project seems to be missing

**Comment by l3d00m** [comment]
Thank you! Good luck with that.

**Comment by l3d00m** [comment]
Didn't you post the api key here on github(I saw some commit about thast).  It's possible that someone deleted the crowdin project or so.

**Comment by moezbhatti** [comment]
Shit, I hope that wasn't it. I didn't realize what that key allowed for

If that's what happened then I'm a complete idiot
I'll e-mail crowdin and see if they can help me out

**Comment by l3d00m** [comment]
Oh, really good luck. Crowdin has a fast and nice support, so I hope the best for you!

**Comment by pille1842** [comment]
Of course I'd also like to add my translations to Crowdin once you figured this out. :)

**Comment by moezbhatti** [comment]
They said they are going to look into it for me tomorrow

**Comment by l3d00m** [comment]
Sounds like it's possible to recover.

**Comment by moezbhatti** [comment]
I hope so!

**Comment by l3d00m** [comment]
Any news?

**Pull request merged**
