### PR TITLE
Make date behave according to Locale

### PR DESCRIPTION
**Pull request by LanderN**
This makes the date under a message behave according to locale of the system

### CODE REVIEW

**Comment by moezbhatti** [comment]
There was another change that dealt with locals for timestamps, and it looks like it's causing some merge conflicts

**Comment by LanderN** [comment]
Oh, I didn't notice that someone else was already looking into this! Guess this change isn't needed anymore then. Although this looks like a cleaner solution than a manual "shouldBeFlipped" test.

**Comment by sm4rk0** [comment]
I was (also) looking into this, but it seems to me that LanderN's changes to DateFormatter are cleaner than mine. So, I propose I rollback my commit to that file in PR #162 and only leave the change to the time picker dialog. Moez?

**Comment by moezbhatti** [comment]
Beautiful

**Comment by moezbhatti** [comment]
@sm4rk0 your change compliments this one, no need to revert!

**Pull request merged**
