### PR TITLE
Fix for #142 and #130, random patches

### LINKED ISSUE #142: Writting Issue
android ICS
When I write it doesn't show suggestions when t9 is on and when I press space it makes the first letter big, like when you start a new sentence.

### PR DESCRIPTION
**Pull request by l3d00m**
PR FOR MASTER instead of develop (was #173)

This should fix #142, it's not the best solution though.
It's not possible to use multiline mode and to use the enter key as Action_send so this is the workaround: http://stackoverflow.com/a/6772713/4026792

Also adds an option for #130, the description of the toggle should probably be changed because my english isn't the best

### CODE REVIEW

**Comment by moezbhatti** [comment]
Going to take a look and test the keyboard stuff now, sorry for taking so long to review this

By the way, just for future reference, this probably should have been 3 separate PRs

1. Lint
2. Mark messages read from notification is cleared
3. The return key issue

**Comment by l3d00m** [comment]
Should I change it?

I will seperate it next time, I'm new to git(hub) and had no idea that new commits on the same branch get added automatically to the pr.

**Comment by moezbhatti** [comment]
Yeah, I can't modify your branch so you'll need to change it

No worries, luckily these are all good changes so we can merge it fine :smile:

**Comment by l3d00m** [comment]
I've removed the lines because it's already defined in the xml file (view_compose.xml or so). (I will link to it later). Auto capitalizing worked for me without that and I thought that's enough in the xml file. Could be my keyboard too (swiftkey).
Enter should send the message if you've checked "new line" for "enter button behaviour" in the settings. It worked at least for me. I'll test that again tomorrow, I've no time today.

**Pull request merged**
