### PR TITLE
Add option to select Google's Lato Font Family.

### PR DESCRIPTION
**Pull request by KyleGospo**
Adds the option to select Google's Lato Font
Changes RobotoTextViewUtils and RobotoTypefaceManager to be generic.
Changes font family option text to reflect actual family. IE:
Regular -> Roboto Regular.

This translation is complete for most languages. Languages vastly
different from English will need some small changes in this area.

Preview: https://i.imgur.com/Mz6goLI.png

### CODE REVIEW

**Comment by moezbhatti** [comment]
View discussion in #121

**Comment by KyleGospo** [comment]
@moezbhatti You may need to re-merge this PR. The fix for two tabs instead of spaces and the vertical centering fix were incorrectly not included in this PR. It's in the branch the PR is based off of now however.

**Comment by moezbhatti** [comment]
I'm don't have a lot of experience managing a repo with multiple contributors, so what's the best way of doing that?

I figure just creating a new PR with the new changes would be a simple solution

**Comment by KyleGospo** [comment]
@moezbhatti Let me do that, as that's most likely the easiest way. One moment.

**Pull request merged**
